In [2]:
import numpy as np
import pandas as pd

In [3]:
max_tickets = 10

prob_of_buying = np.array([1, .4])

prob_of_happening = np.array([1/4, 1/2, 1/4])

price = np.array([100, 200])

In [28]:
possible_actions = [(max(j-i, 0), min(i, j)) \
                        for j in range(0, 3) \
                        for i in range(0, 3) if i <= j]

print(possible_actions)

actions_dict = {i: action for i, action in enumerate(possible_actions)}

#exps = {}
v0 = []
for action in possible_actions:
    customer_array = np.array([[min(ncostumers, action[0]), min(action[1], max(0, ncostumers-action[0]))] \
                                for ncostumers in range(0, 3)])
    #exps[action] = customer_array*prob_of_buying@price@prob_of_happening
    v0 += [customer_array*prob_of_buying@price@prob_of_happening]

v0

[(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]


[0.0, 75.0, 60.0, 100.0, 95.0, 80.0]

In [5]:
P_0_0 = np.eye(11)

In [6]:
pstart_r = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_1_0 = np.array([pstart_r] +[np.roll(pstart_r, i)*3/4 + np.roll(pstart_r, i+1)*1/4 for i in range(0, 10)])
P_1_0

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25]])

In [15]:
pstart_p = np.array([1/2*.4+.4*1/4, 1/4+.6*1/2+.6*1/4, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_0_1 = np.array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]+[np.roll(pstart_p, i) for i in range(0, 10)])
P_0_1

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7]])

In [16]:
P_2_0 = np.array([pstart_r*.75]*2+[np.roll(pstart_r, i)*1/4 + np.roll(pstart_r, i+1)*1/2 for i in range(0, 9)])+ np.eye(11)*1/4
P_2_0

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25]])

In [17]:
pstart_rp = np.array([.1, .65, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_1_1 = np.array([pstart_r*.75]*2+[np.roll(pstart_rp, i) for i in range(0, 9)]) + np.eye(11)/4
P_1_1

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25]])

In [18]:
#pstart_pp = np.array([1/4+1/2*.6, 1/2*.4+1/4*.6*.4, , 0, 0, 0, 0, 0, 0, 0, 0])
pstart_pp = np.array([1/4*.4**2, 1/2*.4+1/2*.6*.4, 1/4+1/2*.6+1/4*.6**2, 0, 0, 0, 0, 0, 0, 0, 0])
P_0_2 = np.array([pstart_r]+[np.array([1-(1/4+1/2*.6+1/4*.6**2), 1/4+1/2*.6+1/4*.6**2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]+[np.roll(pstart_pp, i) for i in range(0, 9)])
P_0_2

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.36, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64]])

In [19]:
[(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]

Pk = [P_0_0, P_1_0, P_0_1, P_2_0, P_1_1, P_0_2]

In [33]:
optimal_policy = {}
optimal_value = {}

v_star = np.zeros(11)

for day in range(15):
    v = v_star
    a, v_star = [], []
    for i in range(max_tickets+1):
        v_temp = [v0[j] + Pk[j][i]@v if sum(actions_dict[j]) <=  i else 0 for j in range(6)]
        v_star += [max(v_temp)]
        
        a_star = np.argmax(v_temp)
        a += [possible_actions[a_star]]
    optimal_value[day] = v_star
    optimal_policy[day] = a
    

Here, we consider the columns to represent how many tickets are left for each day

In [34]:
action_df = pd.DataFrame(optimal_policy).T
action_df['Days left'] = [i for i in range(0, 15)]
action_df.set_index('Days left')

0       1       2       3       4       5       6       7   
Days left                                                                   
0          (0, 0)  (1, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  \
1          (0, 0)  (0, 1)  (1, 1)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)   
2          (0, 0)  (0, 1)  (0, 2)  (1, 1)  (2, 0)  (2, 0)  (2, 0)  (2, 0)   
3          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (1, 1)  (2, 0)  (2, 0)  (2, 0)   
4          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (1, 1)  (2, 0)  (2, 0)   
5          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (2, 0)  (2, 0)   
6          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (1, 1)  (2, 0)   
7          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (1, 1)   
8          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
9          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
10         (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
11         (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
12         (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
13         (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
14         (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   

                8       9      10  
Days left                          
0          (2, 0)  (2, 0)  (2, 0)  
1          (2, 0)  (2, 0)  (2, 0)  
2          (2, 0)  (2, 0)  (2, 0)  
3          (2, 0)  (2, 0)  (2, 0)  
4          (2, 0)  (2, 0)  (2, 0)  
5          (2, 0)  (2, 0)  (2, 0)  
6          (2, 0)  (2, 0)  (2, 0)  
7          (2, 0)  (2, 0)  (2, 0)  
8          (1, 1)  (2, 0)  (2, 0)  
9          (1, 1)  (2, 0)  (2, 0)  
10         (0, 2)  (1, 1)  (2, 0)  
11         (0, 2)  (0, 2)  (1, 1)  
12         (0, 2)  (0, 2)  (0, 2)  
13         (0, 2)  (0, 2)  (0, 2)  
14         (0, 2)  (0, 2)  (0, 2)

In [35]:
value_df = pd.DataFrame(optimal_value).T
value_df['Days left'] = [i for i in range(0, 15)]
value_df.set_index('Days left')

0           1           2           3           4           5   
Days left                                                                    
0          0.0   75.000000  100.000000  100.000000  100.000000  100.000000  \
1          0.0  112.500000  168.750000  193.750000  200.000000  200.000000   
2          0.0  138.750000  224.000000  264.375000  289.062500  298.437500   
3          0.0  157.125000  267.760000  326.430000  361.509375  385.234375   
4          0.0  169.987500  301.646400  380.883400  426.534000  458.932687   
5          0.0  178.991250  327.449696  427.091724  486.930304  525.443136   
6          0.0  185.293875  346.845005  465.282256  541.402734  589.184973   
7          0.0  189.705713  361.274843  496.182801  589.261872  648.938548   
8          0.0  192.793999  371.921728  520.753171  630.357088  703.731782   
9          0.0  194.955799  379.723985  540.008742  664.946420  752.932735   
10         0.0  196.469059  385.409206  554.915502  693.557466  796.260155   
11         0.0  197.528342  389.531991  566.335630  716.866107  833.741508   
12         0.0  198.269839  392.509544  575.006174  735.602990  865.645145   
13         0.0  198.788887  394.652456  581.537799  750.488271  892.406096   
14         0.0  199.152221  396.190016  586.424533  762.190687  914.557660   

                     6            7            8            9           10  
Days left                                                                   
0           100.000000   100.000000   100.000000   100.000000   100.000000  
1           200.000000   200.000000   200.000000   200.000000   200.000000  
2           300.000000   300.000000   300.000000   300.000000   300.000000  
3           396.484375   399.609375   400.000000   400.000000   400.000000  
4           482.115625   494.453125   498.925781   499.902344   500.000000  
5           556.628750   579.404266   592.486914   598.051758   599.682617  
6           624.388256   654.526225   676.981049   690.607463   697.068262  
7           689.803785   723.402420   752.605439   774.773946   788.816059  
8           752.705233   789.672302   822.343311   850.846811   872.742348  
9           812.139803   854.405219   889.143347   921.301434   949.194820  
10          867.305806   916.821386   954.947005   988.709056  1020.235259  
11          917.621264   976.153951  1019.241159  1055.029693  1088.214402  
12          962.749536  1031.726994  1081.388457  1120.422332  1154.836365  
13         1002.590269  1083.010933  1140.751232  1184.383679  1220.885958  
14         1037.247254  1129.652127  1196.747898  1246.366386  1285.999840