In [2]:
import numpy as np
import pandas as pd

In [3]:
max_tickets = 10

prob_of_buying = np.array([1, .4])

prob_of_happening = np.array([1/4, 1/2, 1/4])

price = np.array([100, 200])

In [4]:
possible_actions = [(max(j-i, 0), min(i, j)) \
                        for j in range(0, 3) \
                        for i in range(0, 3) if i <= j]

print(possible_actions)

actions_dict = {i: action for i, action in enumerate(possible_actions)}

exps = {}
v0 = []
for action in possible_actions:
    customer_array = np.array([[min(ncostumers, action[0]), min(action[1], max(0, ncostumers-action[0]))] \
                                for ncostumers in range(0, 3)])
    exps[action] = customer_array*prob_of_buying@price@prob_of_happening
    v0 += [customer_array*prob_of_buying@price@prob_of_happening]

[(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]


In [5]:
P_0_0 = np.eye(11)

In [6]:
pstart_r = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_1_0 = np.array([pstart_r] +[np.roll(pstart_r, i)*3/4 + np.roll(pstart_r, i+1)*1/4 for i in range(0, 10)])
P_1_0

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25]])

In [9]:
pstart_p = np.array([1/2*.4+.4*1/4, 1/4+.6*1/2+.6*1/4, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_0_1 = np.array([pstart_r*3/4] +[np.roll(pstart_p, i)*3/4 for i in range(0, 10)]) + 1/4*np.eye(11)
P_0_1

array([[1.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.225, 0.775, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.225, 0.775, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.225, 0.775, 0.   , 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.225, 0.775, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.225, 0.775, 0.   , 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.225, 0.775, 0.   , 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.225, 0.775, 0.   ,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.225, 0.775,
        0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.225,
        0.775, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0. 

In [10]:
P_2_0 = np.array([pstart_r*.75]*2+[np.roll(pstart_r, i)*1/4 + np.roll(pstart_r, i+1)*1/2 for i in range(0, 9)])+ np.eye(11)*1/4
P_2_0

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25]])

In [12]:
pstart_rp = np.array([.1, .65, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_1_1 = np.array([pstart_r*.75]*2+[np.roll(pstart_rp, i) for i in range(0, 9)]) + np.eye(11)/4
P_1_1

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.1 , 0.65, 0.25]])

In [16]:
#pstart_pp = np.array([1/4+1/2*.6, 1/2*.4+1/4*.6*.4, , 0, 0, 0, 0, 0, 0, 0, 0])
pstart_pp = np.array([1/4*.4**2, 1/2*.4+1/2*.6*.4, 1/4+1/2*.6+1/4*.6**2, 0, 0, 0, 0, 0, 0, 0, 0])
P_0_2 = np.array([pstart_r]+[np.array([1-(1/4+1/2*.6+1/4*.6**2), 1/4+1/2*.6+1/4*.6**2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]+[np.roll(pstart_pp, i) for i in range(0, 9)])
P_0_2

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.36, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.04, 0.32, 0.64]])

In [21]:
[(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]
Pk = [P_0_0, P_1_0, P_0_1, P_2_0, P_1_1, P_0_2]

In [25]:
optimal_policy = {}
optimal_value = {}

v_star = np.zeros(11)

for day in range(15):
    a = []
    v = v_star
    v_star = []
    for i in range(max_tickets+1):
        #print([Pk[j][i].shape for j in range(len(v0))])
        v_temp = [v0[j] + Pk[j][i]@v if sum(actions_dict[j]) <=  i else 0 for j in range(6)]
        v_star += [max(v_temp)]
        
        a_star = np.argmax(v_temp)
        a += [actions_dict[a_star]]
    #print(v_star)
    optimal_value[day] = v_star
    optimal_policy[day] = a
    

Here, we consider the columns to represent how many tickets are left for each day

In [23]:
action_df = pd.DataFrame(optimal_policy).T
action_df['Days left'] = [i for i in range(0, 15)]
action_df.set_index('Days left')

0       1       2       3       4       5       6       7  \
Days left                                                                   
0          (0, 0)  (1, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)   
1          (0, 0)  (0, 1)  (1, 1)  (2, 0)  (2, 0)  (2, 0)  (2, 0)  (2, 0)   
2          (0, 0)  (0, 1)  (0, 2)  (1, 1)  (2, 0)  (2, 0)  (2, 0)  (2, 0)   
3          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (1, 1)  (2, 0)  (2, 0)  (2, 0)   
4          (0, 0)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (1, 1)  (2, 0)  (2, 0)   
5          (0, 0)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (2, 0)  (2, 0)   
6          (0, 0)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (1, 1)  (2, 0)   
7          (0, 0)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)  (1, 1)   
8          (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
9          (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
10         (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)  (0, 2)   
11         (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)   
12         (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)   
13         (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)  (0, 2)   
14         (0, 0)  (0, 1)  (0, 1)  (0, 1)  (0, 1)  (0, 1)  (0, 2)  (0, 2)   

                8       9      10  
Days left                          
0          (2, 0)  (2, 0)  (2, 0)  
1          (2, 0)  (2, 0)  (2, 0)  
2          (2, 0)  (2, 0)  (2, 0)  
3          (2, 0)  (2, 0)  (2, 0)  
4          (2, 0)  (2, 0)  (2, 0)  
5          (2, 0)  (2, 0)  (2, 0)  
6          (2, 0)  (2, 0)  (2, 0)  
7          (2, 0)  (2, 0)  (2, 0)  
8          (2, 0)  (2, 0)  (2, 0)  
9          (1, 1)  (2, 0)  (2, 0)  
10         (0, 2)  (1, 1)  (2, 0)  
11         (0, 2)  (0, 2)  (1, 1)  
12         (0, 2)  (0, 2)  (1, 1)  
13         (0, 2)  (0, 2)  (0, 2)  
14         (0, 2)  (0, 2)  (0, 2)

In [24]:
value_df = pd.DataFrame(optimal_value).T
value_df['Days left'] = [i for i in range(0, 15)]
value_df.set_index('Days left')

0           1           2           3           4           5  \
Days left                                                                    
0          0.0   75.000000  100.000000  100.000000  100.000000  100.000000   
1          0.0  118.125000  168.750000  193.750000  200.000000  200.000000   
2          0.0  151.546875  225.800000  264.937500  289.062500  298.437500   
3          0.0  177.448828  273.007000  327.877875  362.055000  385.375000   
4          0.0  197.522842  311.508105  384.302033  427.556400  459.467287   
5          0.0  213.080202  345.861421  433.536808  489.073071  526.249193   
6          0.0  225.137157  375.985647  476.662420  545.573001  590.644339   
7          0.0  234.481297  402.044736  514.384842  596.738121  651.662234   
8          0.0  241.723005  424.342962  549.108318  642.597336  708.595422   
9          0.0  247.335329  443.253472  581.036113  683.950676  761.096550   
10         0.0  251.684880  459.171890  610.035019  721.390128  809.207453   
11         0.0  255.055782  472.487313  636.090815  756.335228  853.139011   
12         0.0  257.668231  483.565218  659.280027  789.280235  893.479873   
13         0.0  259.692879  492.738396  679.744195  820.030188  930.767995   
14         0.0  261.261981  500.303155  697.667890  848.465840  965.851988   

                     6            7            8            9           10  
Days left                                                                   
0           100.000000   100.000000   100.000000   100.000000   100.000000  
1           200.000000   200.000000   200.000000   200.000000   200.000000  
2           300.000000   300.000000   300.000000   300.000000   300.000000  
3           396.484375   399.609375   400.000000   400.000000   400.000000  
4           482.322344   494.488281   498.925781   499.902344   500.000000  
5           557.203330   579.650064   592.556172   598.060547   599.682617  
6           625.270115   655.076479   677.264907   690.705739   697.089971  
7           691.001982   724.259129   753.171995   775.078008   788.941589  
8           754.642708   790.712966   823.173059   851.420282   873.067400  
9           815.425762   855.885782   890.220963   922.119841   949.770256  
10          872.781411   919.147006   956.241897   989.762165  1021.057725  
11          926.382093   979.912433  1021.033113  1056.211073  1089.234028  
12          976.142432  1037.711788  1084.088454  1121.902180  1155.949016  
13         1022.215925  1092.240317  1144.930080  1186.434172  1222.179606  
14         1064.865158  1143.373619  1203.160790  1249.385108  1287.651086