In [35]:
import numpy as np
import pandas as pd

In [94]:
max_tickets = 10

optimal_policy = {}

In [36]:
prob_of_buying = np.array([1, .4])

prob_of_happening = np.array([1/4, 1/2, 1/4])

price = np.array([100, 200])

E = [[np.array([max(j-i, 0), min(i, j)])*prob_of_buying@price \
        if i <= j else 0 for j in range(0,3)] \
        for i in range(0, 3)]
## cols = that day's demand
## rows = number of premium tickets offered
np.array(E)

array([[  0., 100., 200.],
       [  0.,  80., 180.],
       [  0.,   0., 160.]])

In [101]:
possible_actions = [(max(j-i, 0), min(i, j)) \
                        for j in range(0, 3) \
                        for i in range(0, 3) if i <= j]



print(possible_actions)

actions_dict = {i: action for i, action in enumerate(possible_actions)}

exps = {}
v0 = []
for action in possible_actions:
    #action = (0,0)
    customer_array = np.array([[min(ncostumers, action[0]), min(action[1], max(0, ncostumers-action[0]))] \
                                for ncostumers in range(0, 3)])
    print(customer_array)
    exps[action] = customer_array*prob_of_buying@price@prob_of_happening
    v0 += [customer_array*prob_of_buying@price@prob_of_happening]

v0

[(0, 0), (1, 0), (0, 1), (2, 0), (1, 1), (0, 2)]
[[0 0]
 [0 0]
 [0 0]]
[[0 0]
 [1 0]
 [1 0]]
[[0 0]
 [0 1]
 [0 1]]
[[0 0]
 [1 0]
 [2 0]]
[[0 0]
 [1 0]
 [1 1]]
[[0 0]
 [0 1]
 [0 2]]


[0.0, 75.0, 60.0, 100.0, 95.0, 80.0]

In [38]:
def add_two_tuples(t1, t2):
    return tuple([t1[i]+t2[i] for i in range(len(t1))])

In [39]:
add_two_tuples((1, 2), (3, 4))

(4, 6)

In [136]:
P_0_0 = np.eye(11)
P_0_0

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [141]:
pstart_r = np.array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_1_0 = np.array([pstart_r] +[np.roll(pstart_r, i)*3/4 + np.roll(pstart_r, i+1)*1/4 for i in range(0, 10)])
P_1_0

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.75, 0.25]])

In [153]:
pstart_p = np.array([.4, 0.6, 0, 0, 0, 0, 0, 0, 0, 0, 0])
P_0_1 = np.array([pstart_r*3/4] +[np.roll(pstart_p, i)*3/4 for i in range(0, 10)]) + 1/4*np.eye(11)
P_0_1

array([[1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.3, 0.7]])

In [148]:
P_2_0 = np.array([pstart_r*.75]*2+[np.roll(pstart_r, i)*1/4 + np.roll(pstart_r, i+1)*1/2 for i in range(0, 9)])+ np.eye(11)*1/4
P_2_0

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.5 , 0.25]])

In [163]:
P_1_1 = np.array([pstart_r*.75]*2+[np.roll(pstart_p*pstart_r, i+1)*1/4 + np.roll(pstart_p, i)*1/2 for i in range(0, 9)]) + np.eye(11)*1/4
P_1_1

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.75, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.2 , 0.4 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.2 , 0.4 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.2 , 0.4 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.2 , 0.4 , 0.25, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.25, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.25, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.25, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.2 , 0.4 , 0.25]])

In [80]:
pstart_p2 = np.array([.4**2, 2*.4*.6, .6**2, 0, 0, 0, 0, 0, 0, 0, 0])
P_0_2 = np.array([pstart_r]+[np.array([.4**2+2*.4*.6, .6**2, 0, 0, 0, 0, 0, 0, 0, 0, 0])]+[np.roll(pstart_p2, i) for i in range(0, 9)])
P_0_2

array([[1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.64, 0.36, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.16, 0.48, 0.36, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.16, 0.48, 0.36, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.16, 0.48, 0.36, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.16, 0.48, 0.36, 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.16, 0.48, 0.36, 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.16, 0.48, 0.36, 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.16, 0.48, 0.36, 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.16, 0.48, 0.36, 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.16, 0.48, 0.36]])

In [137]:
Pk = [P_0_0, P_0_1, P_1_0, P_2_0, P_1_1, P_0_2]

In [138]:
action = 0
state = 7

v0

[0.0, 75.0, 60.0, 100.0, 95.0, 80.0]

In [164]:
v_star = np.zeros(11)

for day in range(15):
    a = []
    v = v_star
    v_star = []
    for i in range(max_tickets+1):
        #print([Pk[j][i].shape for j in range(len(v0))])
        v_temp = [v0[j] + Pk[j][i]@v if sum(actions_dict[j]) <=  i else 0 for j in range(6)]
        v_star += [max(v_temp)]
        a_star = np.argmax(v_temp)
        a += [actions_dict[a_star]]
    #print(v_star)        
    optimal_policy[day] = a

    print(a)
    

[(0, 0), (1, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0)]
[(0, 0), (1, 0), (1, 0), (1, 1), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 1), (2, 0), (2, 0), (2, 0), (2, 0), (2, 0)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 1), (1, 1), (2, 0), (2, 0), (2, 0)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 1), (1, 1), (1, 1), (2, 0)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 1), (1, 1), (1, 1)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 1), (1, 1)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 1), (1, 1)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 1)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0)]
[(0, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0), (1, 0)]
[(0, 0), (1, 0), (1, 

In [133]:
actions_dict

{0: (0, 0), 1: (1, 0), 2: (0, 1), 3: (2, 0), 4: (1, 1), 5: (0, 2)}

In [109]:
anew = []
vnew_star = []

for i in range(max_tickets+1):
    vnew = [value if sum(actions_dict[j]) + Pk[j][i]@v_star <= i else 0 for j, value in enumerate(v0) ]
    vnew_star += [max(v)]
    anew_star = np.argmax(v)
    anew += [a_star]

In [112]:
vnew_star

[100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0, 100.0]